### PR TITLE
feat: add getThumbnail method

### PR DESCRIPTION
**Pull request by Danielwinkelmann**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
add getThumbnail method, to generate image url with given options from the Directus file API

## Checklist:
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Intevel** [comment]
Hey, thanks for your PR @Danielwinkelmann. ❤️

Can you update the playground to test it?

**Comment by Danielwinkelmann** [comment]
Hey @Intevel, I upload an image to the Directus Sample CMS and add the file-id to the playground.
You have to enable public file access for the public Role to get it working.

**Review by Intevel — APPROVED** [review]
Looks good to me, good job. 
_Test with playground was successful_ 💯

**Comment by Danielwinkelmann** [comment]
Thanks :-)
add another PR to add some typescript support

**Pull request merged**
