### PR TITLE
feat: token authentification

### LINKED ISSUE #31: Use access_token authentication method
### Is your feature request related to a problem? Please describe.
You currently can't use the Directus access token method to authenticate to the API.
Ie. I share the "token" from the User > Admin Settings section and provide that in the Query String or the Authorization Bearer header.

### Describe the solution you'd like
login should accept a {"token" OR { email:  string, password: string }

```ts
<script setup lang="ts">
const { login } = useDirectusAuth();
const router = useRouter();

const onSubmit = async () => {
  try {
    await login({ token: "" });
  } catch (e) {}
};
</script>
```

### PR DESCRIPTION
**Pull request by Intevel**
Implemented the authentification option for static tokens, normal token after login have priority!

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

Will close #31 
And answer the newest discussion #51 

@craigharman @mklueh

### CODE REVIEW

**Comment by mklueh** [comment]
@Intevel after cursing Directus's permission model and creating dozens of users / roles for two hours while testing on the master branch I finally realized that I was on the wrong branch and can confirm now, that it is working 😊

**Comment by Intevel** [comment]
Thanks for your time 😂

**Comment by Intevel** [comment]
I will merge & release it tomorrow.

**Comment by mklueh** [comment]
@Intevel thank you for your effort ;)

**Comment by vanling** [comment]
Thanks!

**Pull request merged**
