### PR TITLE
Fixed ability to install from Github + Fixed typo

### PR DESCRIPTION
**Pull request by amerkay**
I was trying to get acceptInvite, and inviteUsers functions to work, so:
1. I needed to install with `pnpm add github:Intevel/nuxt-directus`. This is when I got the error that tsconfig.json `extends` does not exist. Fixed by having the minimal required config instead. 
> File ./playground/.nuxt/tsconfig.json does not exists.
2. Fixed a typo: : inviteAccept renamed to acceptInvite.

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by amerkay** [comment]
Hi again, 

Another commit adds 2 config vars: sameSiteRefreshToken and isSecureRefreshToken, https://github.com/Intevel/nuxt-directus/pull/172/commits/013437db774cc7805c9bcebe9a875ec73cd05b28

This is to fix having Same-Site = "none" with secure=false, which shows a warning in console logs.

Docs will need to be updated accordingly.

Cheers!

**Comment by amerkay** [comment]
More commits:
1. Bug fix: In `nuxt generate` SSR mode, the hook `app:created`  is called **after** the auth middleware (as in [the docs](https://nuxt-directus.netlify.app/examples/redirectuserlogin)). Which made the auth middeware malfunction, as `useDirectusUser()` would still be null.
2. Renamed the added cookie variables, and update docs:
    - cookieMaxAge (from maxAgeRefreshToken) <- **Note, this is a breaking change**
    - cookieSameSite (from sameSiteRefreshToken)
    - cookieSecure (from isSecureRefreshToken)

**Comment by Intevel** [comment]
@amerkay Thanks for this, great work. I will review it in the next days, are there any breaking changes?

**Comment by amerkay** [comment]
> @amerkay Thanks for this, great work. I will review it in the next days, are there any breaking changes?

Thanks @Intevel! 

Only this (see my last comment):
> Renamed config var to `cookieMaxAge` (from `maxAgeRefreshToken`) 

Cheers!

**Comment by casualmatt** [comment]
@amerkay 
 is the change from `maxAgeRefreshToken ` to `cookieMaxAge` just a rename or there is more to it?

**Comment by amerkay** [comment]
> @amerkay is the change from `maxAgeRefreshToken ` to `cookieMaxAge` just a rename, or is there more to it?

Just a rename, as it's not really just the for the RefreshToken, it's for all 3 cookies. See [modifications in useDirectusToken composable](https://github.com/Intevel/nuxt-directus/commit/013437db774cc7805c9bcebe9a875ec73cd05b28). Note this is before the rename.

**Comment by casualmatt** [comment]
@amerkay I have re-introduced the support for maxAgeRefreshToken to keep backward compatibility, we will remove it in future versions.  

Can you proceed and double-test it, so that we are sure with both setting the behavior is the same?

**Comment by amerkay** [comment]
Fixed minor conflict.

**Review by casualmatt — APPROVED** [review]

**Review by Intevel — APPROVED** [review]
LGTM, good work

**Pull request merged**
