### PR TITLE
fix: return type for getItems

### PR DESCRIPTION
**Pull request by ranseur92**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fixes the getItems typescript return type to more appropriately match the request.  Resolves: #145 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by casualmatt** [comment]
Hello @ranseur92,
Ty, for your PR, it looks pretty st8 forward. Can we proceed with revision and merge, or do you need to commit something else?

**Comment by ranseur92** [comment]
Nothing else is needed. can be processed :)

**Review by Intevel — APPROVED** [review]
LGTM, Thanks

**Comment by Intevel** [comment]
I will today

**Pull request merged**
